server {
    listen 80;
    
    # 1. Servir la Aplicación Web (React Vite)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto permite que React Router maneje las rutas
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy inverso al Backend
    location /api/ {
        # IMPORTANTE: "backend" debe coincidir con el nombre del servicio en docker-compose
        proxy_pass http://backend:3000;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}