server {
    listen 80;
    
    # 1. Servir la Aplicación Web (React/Expo)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Redirigir llamadas de API al Backend interno
    location /api/ {
        # 'backend' es el nombre del servicio en tu Dockge/Compose
        # '3000' es el puerto INTERNO donde escucha Node.js
        proxy_pass http://backend:3000;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}